### ISSUE TITLE
Packages configuration

### ISSUE THREAD

**Issue by mquandalle** [MeteorCommunity/discussions#58] opened 2014-12-29 17:02 UTC
We need a way for meteor application developers to provide package settings/configuration. Currently every package has to implement its own mechanism to retrieve developer's input, the most common being to handle a `myPackage.json` file using the plugin API (for instance https://github.com/raix/push/#config).

This probably should be considered as part of the upcoming `meteor.js` file format refactoring.

**Comment by raix** [comment] 2014-12-29 17:46
@mquandalle I did actually try to create a separate package "config" that other packages could depend on. It mounted it self in Plugin global scope as `Configuration`

A package could in theory depend on the config package and define package config:

``` js
// push.config
Configuration('push', function(config) {
  // Validate the config - throw on error
  check(config, {
    name: String
  });
}, {
  'web.browser': configureBrowserVersion,
  'web.cordova': configureCordovaVersion,
  'os': configureServerVersion,
});
```

Where `configureServerVersion` would look like:

``` js
  var configureServerVersion = function(config) {
    // Return configuration / javascript
    // For client version we filter off sensitive data
    // The push package actually replaces 'key.pem' with Assets.getText('key.pem');
    // tapping into the apps private folder for key/cert - a small but important detail when
    // thinking about package configuration - This should be solved with a nicer api...
    return 'Push.init(' + JSON.stringify(config) + ');';
  };
```

Problem with this package is that it cant live in global scope safely.

Source handlers only support the extension - I'm really against what I did in the push package - "claiming" the whole `*.push.json` namespace - And I'm not sure if json is the best format.

## 

I'm sorry about cc you @glasser - but I think its a thing we package writers struggle with, and have been for a long time. Is there any change we could add/pr something like `Configure` on the `Plugin` scope - is it even possible to solve like that - would be great to hear MDG's thoughts on this?

I know that this would be harder to add in isopack since it would have to know about affected files and conditions. But it would be nice if we could allow a kind of "runtime" build - simply adding extra files.

## 

Its related / duplicate of #11

**Comment by Sivli-Embir** [comment] 2015-01-28 17:59
IMO I feel that this extends to package consumers as well:

For example currently I have both bootstrap (via houston) and semantic ui (for my app). But we are mostly a mobile product and want to move to ionic. But we have a web only too that needs to stay semantic-ui. How to I tell meteor to only load ionic on Cordova and not put it in web. How to I keep both bootstrap and semantic out of Cordova? 

Sure I could move my app into packages and specify their location but even then it does not fix the Cordova problem. I cleaner solution would be much better. 

And this has been said before but how do I load only pieces of a package. Again looking at mostly CSS frameworks but I would love that for kestanous:herald. Currently I use extension packages to keep from polluting a users app but it would be great if they could tell Herald to only add email and not push logic.

**Closed as completed** 2018-06-18 14:13 UTC
